language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"

install: 
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "py.test --cov=qcic --cov-report=term-missing"
after_success:
    coveralls
